name: Build NoParticle Native ARM64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up NDK
      run: |
        echo "NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

    - name: Compile C++ Code
      run: |
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang++ \
        -shared \
        -fPIC \
        -O2 \
        -o NoParticle.so \
        main.cpp \
        -llog -landroid -ldl

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NoParticle
        path: NoParticle.so
